# Generated by Django 4.2.13 on 2024-06-27 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine_type',
        ),
    ]
