# Generated by Django 4.2.13 on 2024-06-28 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurants', '0003_restaurant_opening_hours_restaurant_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_added', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
