# Generated by Django 4.2.13 on 2024-06-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='cuisine_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
