# Generated by Django 4.2.13 on 2024-06-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0003_migrate_cuisine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
